// prototype/src/components/GemsTracker.tsx
import { Diamond } from "lucide-react";
import { TOTAL_GEMS } from "@/lib/appState";

export default function GemsTracker({ filled }: { filled: number }) {
  return (
    <div className="rounded-2xl border border-border bg-card/60 p-5 mb-6">
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs uppercase tracking-widest text-muted-foreground">Migration Progress</div>
        <div className="ticker-mono text-xs text-primary">
          {filled}/{TOTAL_GEMS} Vue 3 Gems
        </div>
      </div>
      <div className="flex items-center justify-between gap-2">
        {Array.from({ length: TOTAL_GEMS }).map((_, i) => {
          const on = i < filled;
          return (
            <div key={i} className="flex-1 flex items-center justify-center">
              <Diamond
                className={`h-10 w-10 transition-all ${
                  on
                    ? "text-primary fill-primary/40 drop-shadow-[0_0_12px_hsl(var(--primary)/0.8)] animate-pulse"
                    : "text-muted-foreground/30"
                }`}
                strokeWidth={1.5}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}

// product/app/components/redeem/GemsTracker.vue
<script setup lang="ts">
import { TOTAL_GEMS } from '#shared/constants/game'

const props = defineProps<{ filled: number; label?: string }>()
const lit = (i: number) => i < props.filled
</script>

<template>
  <div class="rounded-2xl border border-white/10 bg-white/5 p-5 mb-6">
    <div class="flex items-center justify-between mb-3">
      <div class="text-xs uppercase tracking-widest text-slate-400">
        {{ label ?? 'Migration Progress' }}
      </div>
      <div class="ticker-mono text-xs text-emerald-300">
        {{ filled }}/{{ TOTAL_GEMS }} Vue 3 Gems
      </div>
    </div>
    <div class="flex items-center justify-between gap-2">
      <div v-for="i in TOTAL_GEMS" :key="i" class="flex-1 flex items-center justify-center">
        <UIcon
          name="i-lucide-diamond"
          :class="[
            'h-10 w-10 transition-all',
            lit(i - 1) ? 'text-emerald-400 animate-gem-pulse' : 'text-slate-700',
          ]"
        />
      </div>
    </div>
  </div>
</template>
